version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: H0CgsJ6Uk9
      MYSQL_DATABASE: ecommerce-insights
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    command:
      --default-authentication-plugin=mysql_native_password

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    restart: always
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: mysql://appuser:apppassword@mysql:3306/appdb
    depends_on:
      - mysql
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

volumes:
  mysql-data:
